-- Islam-Kinderakademie: leeres Datenmodell für Accounts, Kurse und Lernfortschritt.
-- Alle fachlichen Tabellen verwenden automatisch erzeugte bigint-Primärschlüssel.

-- Vorhandenes Account-Schema abgleichen, ohne bestehende Daten zu löschen.
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  display_name text not null,
  avatar_url text,
  created_at timestamp without time zone not null default now()
);

alter table public.profiles add column if not exists auth_user_id uuid;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles
  add column if not exists created_at timestamp without time zone not null default now();

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles (id) on delete cascade,
  role text not null default 'parent' check (role in ('parent', 'teacher', 'admin')),
  created_at timestamp without time zone not null default now(),
  unique (profile_id, role)
);

alter table public.user_roles add column if not exists profile_id bigint;
alter table public.user_roles add column if not exists role text;
alter table public.user_roles
  add column if not exists created_at timestamp without time zone not null default now();

create unique index if not exists profiles_auth_user_id_key
  on public.profiles (auth_user_id);
create unique index if not exists user_roles_profile_id_role_key
  on public.user_roles (profile_id, role);
create index if not exists user_roles_profile_id_idx
  on public.user_roles (profile_id);

-- Neue Auth-Nutzer erhalten automatisch ein Profil und die Elternrolle.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_profile_id bigint;
begin
  insert into public.profiles (auth_user_id, display_name)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      split_part(coalesce(new.email, 'Mein Konto'), '@', 1)
    )
  )
  returning id into new_profile_id;

  insert into public.user_roles (profile_id, role)
  values (new_profile_id, 'parent');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

create table public.academy_years (
  id bigint generated by default as identity primary key,
  title text not null,
  starts_on date not null,
  ends_on date not null,
  is_active boolean not null default false,
  created_at timestamp without time zone not null default now(),
  constraint academy_years_date_order check (ends_on >= starts_on)
);

create table public.children (
  id bigint generated by default as identity primary key,
  parent_profile_id bigint not null references public.profiles (id) on delete cascade,
  display_name text not null,
  birth_date date,
  age_group text not null check (age_group in ('5-8', '9-12')),
  avatar_key text,
  created_at timestamp without time zone not null default now()
);

create table public.learning_journeys (
  id bigint generated by default as identity primary key,
  academy_year_id bigint not null references public.academy_years (id) on delete cascade,
  age_group text not null check (age_group in ('5-8', '9-12')),
  title text not null,
  description text,
  position integer not null default 0 check (position >= 0),
  is_published boolean not null default false,
  created_at timestamp without time zone not null default now(),
  unique (academy_year_id, age_group, position)
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  learning_journey_id bigint not null references public.learning_journeys (id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'published', 'archived')),
  position integer not null default 0 check (position >= 0),
  publish_at timestamp without time zone,
  replay_url text,
  created_at timestamp without time zone not null default now(),
  unique (learning_journey_id, position)
);

create table public.lesson_steps (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  step_type text not null
    check (step_type in ('start', 'discover', 'explain', 'quiz', 'challenge')),
  title text,
  content jsonb not null default '{}'::jsonb,
  position integer not null default 0 check (position >= 0),
  created_at timestamp without time zone not null default now(),
  unique (lesson_id, position)
);

create table public.groups (
  id bigint generated by default as identity primary key,
  academy_year_id bigint not null references public.academy_years (id) on delete cascade,
  teacher_profile_id bigint references public.profiles (id) on delete set null,
  name text not null,
  age_group text not null check (age_group in ('5-8', '9-12')),
  created_at timestamp without time zone not null default now()
);

create table public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups (id) on delete cascade,
  child_id bigint not null references public.children (id) on delete cascade,
  created_at timestamp without time zone not null default now(),
  unique (group_id, child_id)
);

create table public.live_sessions (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  group_id bigint references public.groups (id) on delete set null,
  title text,
  starts_at timestamp with time zone not null,
  ends_at timestamp with time zone not null,
  meeting_url text,
  replay_url text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'live', 'completed', 'cancelled')),
  created_at timestamp without time zone not null default now(),
  constraint live_sessions_time_order check (ends_at > starts_at)
);

create table public.child_lesson_progress (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children (id) on delete cascade,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed')),
  progress_percent smallint not null default 0
    check (progress_percent between 0 and 100),
  last_opened_at timestamp without time zone,
  completed_at timestamp without time zone,
  created_at timestamp without time zone not null default now(),
  unique (child_id, lesson_id)
);

create table public.child_step_progress (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children (id) on delete cascade,
  lesson_step_id bigint not null references public.lesson_steps (id) on delete cascade,
  completed_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now(),
  unique (child_id, lesson_step_id)
);

create table public.submissions (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children (id) on delete cascade,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  lesson_step_id bigint references public.lesson_steps (id) on delete set null,
  submission_type text not null
    check (submission_type in ('confirmation', 'text', 'audio', 'image')),
  text_value text,
  storage_path text,
  submitted_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now()
);

create table public.badges (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon_key text not null,
  created_at timestamp without time zone not null default now()
);

create table public.child_badges (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children (id) on delete cascade,
  badge_id bigint not null references public.badges (id) on delete cascade,
  lesson_id bigint references public.lessons (id) on delete set null,
  awarded_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now(),
  unique (child_id, badge_id)
);

create table public.media_assets (
  id bigint generated by default as identity primary key,
  uploaded_by_profile_id bigint references public.profiles (id) on delete set null,
  media_type text not null check (media_type in ('image', 'audio', 'video', 'document')),
  bucket_name text not null default 'academy-media',
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  created_at timestamp without time zone not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  sender_profile_id bigint references public.profiles (id) on delete set null,
  recipient_profile_id bigint references public.profiles (id) on delete cascade,
  group_id bigint references public.groups (id) on delete cascade,
  audience text not null default 'all' check (audience in ('all', 'profile', 'group')),
  subject text not null,
  body text not null,
  published_at timestamp without time zone,
  created_at timestamp without time zone not null default now(),
  constraint messages_audience_target check (
    (audience = 'all' and recipient_profile_id is null and group_id is null)
    or (audience = 'profile' and recipient_profile_id is not null and group_id is null)
    or (audience = 'group' and recipient_profile_id is null and group_id is not null)
  )
);

-- Indizes für alle Fremdschlüssel und häufigen Filter.
create index children_parent_profile_id_idx on public.children (parent_profile_id);
create index learning_journeys_academy_year_id_idx on public.learning_journeys (academy_year_id);
create index lessons_learning_journey_id_idx on public.lessons (learning_journey_id);
create index lessons_status_idx on public.lessons (status);
create index lesson_steps_lesson_id_idx on public.lesson_steps (lesson_id);
create index groups_academy_year_id_idx on public.groups (academy_year_id);
create index groups_teacher_profile_id_idx on public.groups (teacher_profile_id);
create index group_members_group_id_idx on public.group_members (group_id);
create index group_members_child_id_idx on public.group_members (child_id);
create index live_sessions_lesson_id_idx on public.live_sessions (lesson_id);
create index live_sessions_group_id_idx on public.live_sessions (group_id);
create index live_sessions_starts_at_idx on public.live_sessions (starts_at);
create index child_lesson_progress_child_id_idx on public.child_lesson_progress (child_id);
create index child_lesson_progress_lesson_id_idx on public.child_lesson_progress (lesson_id);
create index child_step_progress_child_id_idx on public.child_step_progress (child_id);
create index child_step_progress_lesson_step_id_idx on public.child_step_progress (lesson_step_id);
create index submissions_child_id_idx on public.submissions (child_id);
create index submissions_lesson_id_idx on public.submissions (lesson_id);
create index submissions_lesson_step_id_idx on public.submissions (lesson_step_id);
create index child_badges_child_id_idx on public.child_badges (child_id);
create index child_badges_badge_id_idx on public.child_badges (badge_id);
create index media_assets_uploaded_by_profile_id_idx on public.media_assets (uploaded_by_profile_id);
create index messages_recipient_profile_id_idx on public.messages (recipient_profile_id);
create index messages_group_id_idx on public.messages (group_id);
create index messages_published_at_idx on public.messages (published_at);

-- Wiederverwendbare, RLS-sichere Zugriffshelfer.
create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select p.id
  from public.profiles p
  where p.auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function public.has_account_role(required_role text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.profile_id = public.current_profile_id()
      and ur.role::text = required_role
  )
$$;

create or replace function public.is_academy_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.profile_id = public.current_profile_id()
      and ur.role::text in ('teacher', 'admin')
  )
$$;

create or replace function public.owns_child(target_child_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.children c
    where c.id = target_child_id
      and c.parent_profile_id = public.current_profile_id()
  )
$$;

create or replace function public.can_access_group(target_group_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_academy_staff()
    or exists (
      select 1
      from public.group_members gm
      join public.children c on c.id = gm.child_id
      where gm.group_id = target_group_id
        and c.parent_profile_id = public.current_profile_id()
    )
$$;
