-- Neuer Lektionsablauf: Einstiegstext, geplanter Live-Unterricht und
-- eigenständiges Multiple-Choice-Quiz mit serverseitiger Auswertung.

alter table public.lessons
add column if not exists intro_text text not null default '';

update public.lessons as lesson
set intro_text = coalesce(
  (
    select nullif(trim(step.content ->> 'text'), '')
    from public.lesson_steps as step
    where step.lesson_id = lesson.id
      and step.step_type = 'start'
    order by step.position, step.id
    limit 1
  ),
  nullif(trim(lesson.description), ''),
  ''
)
where lesson.intro_text = '';

create table public.lesson_quizzes (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null unique references public.lessons (id) on delete cascade,
  title text not null,
  description text,
  passing_percent smallint not null default 70 check (passing_percent between 0 and 100),
  is_published boolean not null default false,
  created_at timestamp without time zone not null default now()
);

create table public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.lesson_quizzes (id) on delete cascade,
  question_text text not null,
  position integer not null default 0 check (position >= 0),
  created_at timestamp without time zone not null default now(),
  unique (quiz_id, position)
);

create table public.quiz_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.quiz_questions (id) on delete cascade,
  option_text text not null,
  position integer not null default 0 check (position >= 0),
  created_at timestamp without time zone not null default now(),
  unique (question_id, position),
  unique (id, question_id)
);

-- Die richtige Antwort liegt absichtlich getrennt von den sichtbaren Optionen.
-- Dadurch können Kinder die Lösung nicht über die normale Datenabfrage auslesen.
create table public.quiz_answer_keys (
  id bigint generated by default as identity primary key,
  question_id bigint not null unique references public.quiz_questions (id) on delete cascade,
  correct_option_id bigint not null,
  explanation text,
  created_at timestamp without time zone not null default now(),
  foreign key (correct_option_id, question_id)
    references public.quiz_options (id, question_id)
    on delete cascade
);

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  child_id bigint not null references public.children (id) on delete cascade,
  quiz_id bigint not null references public.lesson_quizzes (id) on delete cascade,
  correct_answers integer not null check (correct_answers >= 0),
  total_questions integer not null check (total_questions > 0),
  score_percent smallint not null check (score_percent between 0 and 100),
  passed boolean not null default false,
  submitted_at timestamp without time zone not null default now(),
  created_at timestamp without time zone not null default now()
);

create table public.quiz_attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.quiz_attempts (id) on delete cascade,
  question_id bigint not null references public.quiz_questions (id) on delete cascade,
  selected_option_id bigint not null,
  is_correct boolean not null,
  created_at timestamp without time zone not null default now(),
  unique (attempt_id, question_id),
  foreign key (selected_option_id, question_id)
    references public.quiz_options (id, question_id)
    on delete cascade
);

create index lesson_quizzes_lesson_id_idx on public.lesson_quizzes (lesson_id);
create index quiz_questions_quiz_id_idx on public.quiz_questions (quiz_id);
create index quiz_options_question_id_idx on public.quiz_options (question_id);
create index quiz_answer_keys_correct_option_id_idx on public.quiz_answer_keys (correct_option_id);
create index quiz_attempts_child_id_idx on public.quiz_attempts (child_id);
create index quiz_attempts_quiz_id_idx on public.quiz_attempts (quiz_id);
create index quiz_attempt_answers_attempt_id_idx on public.quiz_attempt_answers (attempt_id);
create index quiz_attempt_answers_question_id_idx on public.quiz_attempt_answers (question_id);
create index quiz_attempt_answers_selected_option_id_idx on public.quiz_attempt_answers (selected_option_id);

alter table public.lesson_quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_options enable row level security;
alter table public.quiz_answer_keys enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_attempt_answers enable row level security;

create policy "Members can read published lesson quizzes"
on public.lesson_quizzes
for select
to authenticated
using (
  public.is_academy_staff()
  or (
    is_published
    and exists (
      select 1
      from public.lessons as lesson
      join public.learning_journeys as journey on journey.id = lesson.learning_journey_id
      join public.academy_years as academy_year on academy_year.id = journey.academy_year_id
      where lesson.id = lesson_quizzes.lesson_id
        and lesson.status = 'published'
        and journey.is_published
        and academy_year.is_active
    )
  )
);

create policy "Staff can manage lesson quizzes"
on public.lesson_quizzes
for all
to authenticated
using (public.is_academy_staff())
with check (public.is_academy_staff());

create policy "Members can read published quiz questions"
on public.quiz_questions
for select
to authenticated
using (
  public.is_academy_staff()
  or exists (
    select 1
    from public.lesson_quizzes as quiz
    join public.lessons as lesson on lesson.id = quiz.lesson_id
    join public.learning_journeys as journey on journey.id = lesson.learning_journey_id
    join public.academy_years as academy_year on academy_year.id = journey.academy_year_id
    where quiz.id = quiz_questions.quiz_id
      and quiz.is_published
      and lesson.status = 'published'
      and journey.is_published
      and academy_year.is_active
  )
);

create policy "Staff can manage quiz questions"
on public.quiz_questions
for all
to authenticated
using (public.is_academy_staff())
with check (public.is_academy_staff());

create policy "Members can read published quiz options"
on public.quiz_options
for select
to authenticated
using (
  public.is_academy_staff()
  or exists (
    select 1
    from public.quiz_questions as question
    join public.lesson_quizzes as quiz on quiz.id = question.quiz_id
    join public.lessons as lesson on lesson.id = quiz.lesson_id
    join public.learning_journeys as journey on journey.id = lesson.learning_journey_id
    join public.academy_years as academy_year on academy_year.id = journey.academy_year_id
    where question.id = quiz_options.question_id
      and quiz.is_published
      and lesson.status = 'published'
      and journey.is_published
      and academy_year.is_active
  )
);

create policy "Staff can manage quiz options"
on public.quiz_options
for all
to authenticated
using (public.is_academy_staff())
with check (public.is_academy_staff());

create policy "Staff can manage quiz answer keys"
on public.quiz_answer_keys
for all
to authenticated
using (public.is_academy_staff())
with check (public.is_academy_staff());

create policy "Families and staff can read quiz attempts"
on public.quiz_attempts
for select
to authenticated
using (public.owns_child(child_id) or public.is_academy_staff());

create policy "Staff can delete quiz attempts"
on public.quiz_attempts
for delete
to authenticated
using (public.is_academy_staff());

create policy "Families and staff can read quiz attempt answers"
on public.quiz_attempt_answers
for select
to authenticated
using (
  public.is_academy_staff()
  or exists (
    select 1
    from public.quiz_attempts as attempt
    where attempt.id = quiz_attempt_answers.attempt_id
      and public.owns_child(attempt.child_id)
  )
);

grant select, insert, update, delete on table
  public.lesson_quizzes,
  public.quiz_questions,
  public.quiz_options,
  public.quiz_answer_keys
to authenticated;

grant select, delete on table public.quiz_attempts to authenticated;
grant select on table public.quiz_attempt_answers to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create or replace function public.save_multiple_choice_quiz(
  target_lesson_id bigint,
  quiz_title text,
  quiz_description text,
  required_passing_percent integer,
  publish_quiz boolean,
  question_definitions jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved_quiz_id bigint;
  saved_question_id bigint;
  saved_option_id bigint;
  correct_option_id bigint;
  question_definition jsonb;
  option_definition jsonb;
  question_position integer;
  option_position integer;
  correct_option_count integer;
begin
  if not public.is_academy_staff() then
    raise exception 'Academy staff role required';
  end if;

  if not exists (select 1 from public.lessons where id = target_lesson_id) then
    raise exception 'Lesson not found';
  end if;

  if coalesce(nullif(trim(quiz_title), ''), '') = '' then
    raise exception 'Quiz title required';
  end if;

  if required_passing_percent not between 0 and 100 then
    raise exception 'Passing percent must be between 0 and 100';
  end if;

  if coalesce(jsonb_typeof(question_definitions), 'null') <> 'array'
    or jsonb_array_length(question_definitions) = 0 then
    raise exception 'At least one quiz question is required';
  end if;

  insert into public.lesson_quizzes (
    lesson_id,
    title,
    description,
    passing_percent,
    is_published
  )
  values (
    target_lesson_id,
    trim(quiz_title),
    nullif(trim(quiz_description), ''),
    required_passing_percent,
    publish_quiz
  )
  on conflict (lesson_id) do update
  set
    title = excluded.title,
    description = excluded.description,
    passing_percent = excluded.passing_percent,
    is_published = excluded.is_published
  returning id into saved_quiz_id;

  -- Bei strukturellen Aenderungen beginnen Versuche und Fortschritt neu.
  delete from public.quiz_attempts where quiz_id = saved_quiz_id;
  delete from public.child_lesson_progress where lesson_id = target_lesson_id;
  delete from public.quiz_questions where quiz_id = saved_quiz_id;

  question_position := 0;
  for question_definition in
    select value from jsonb_array_elements(question_definitions)
  loop
    if coalesce(nullif(trim(question_definition ->> 'question_text'), ''), '') = '' then
      raise exception 'Every quiz question needs text';
    end if;

    if coalesce(jsonb_typeof(question_definition -> 'options'), 'null') <> 'array'
      or jsonb_array_length(question_definition -> 'options') < 2 then
      raise exception 'Every quiz question needs at least two options';
    end if;

    select count(*)
    into correct_option_count
    from jsonb_array_elements(question_definition -> 'options') as option_row(value)
    where coalesce((option_row.value ->> 'is_correct')::boolean, false);

    if correct_option_count <> 1 then
      raise exception 'Every quiz question needs exactly one correct option';
    end if;

    insert into public.quiz_questions (quiz_id, question_text, position)
    values (saved_quiz_id, trim(question_definition ->> 'question_text'), question_position)
    returning id into saved_question_id;

    option_position := 0;
    correct_option_id := null;

    for option_definition in
      select value from jsonb_array_elements(question_definition -> 'options')
    loop
      if coalesce(nullif(trim(option_definition ->> 'option_text'), ''), '') = '' then
        raise exception 'Every quiz option needs text';
      end if;

      insert into public.quiz_options (question_id, option_text, position)
      values (saved_question_id, trim(option_definition ->> 'option_text'), option_position)
      returning id into saved_option_id;

      if coalesce((option_definition ->> 'is_correct')::boolean, false) then
        correct_option_id := saved_option_id;
      end if;

      option_position := option_position + 1;
    end loop;

    insert into public.quiz_answer_keys (question_id, correct_option_id, explanation)
    values (
      saved_question_id,
      correct_option_id,
      nullif(trim(question_definition ->> 'explanation'), '')
    );

    question_position := question_position + 1;
  end loop;

  return saved_quiz_id;
end;
$$;

create or replace function public.submit_multiple_choice_quiz(
  target_child_id bigint,
  target_quiz_id bigint,
  submitted_answers jsonb
)
returns table (
  attempt_id bigint,
  correct_answers integer,
  total_questions integer,
  score_percent integer,
  passed boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  quiz_lesson_id bigint;
  required_percent integer;
  created_attempt_id bigint;
  question_count integer;
  valid_answer_count integer;
  correct_count integer;
  calculated_percent integer;
  did_pass boolean;
begin
  if not public.owns_child(target_child_id) and not public.is_academy_staff() then
    raise exception 'Child access required';
  end if;

  select quiz.lesson_id, quiz.passing_percent
  into quiz_lesson_id, required_percent
  from public.lesson_quizzes as quiz
  join public.lessons as lesson on lesson.id = quiz.lesson_id
  join public.learning_journeys as journey on journey.id = lesson.learning_journey_id
  join public.academy_years as academy_year on academy_year.id = journey.academy_year_id
  where quiz.id = target_quiz_id
    and quiz.is_published
    and lesson.status = 'published'
    and journey.is_published
    and academy_year.is_active;

  if quiz_lesson_id is null then
    raise exception 'Published quiz not found';
  end if;

  if coalesce(jsonb_typeof(submitted_answers), 'null') <> 'array' then
    raise exception 'Quiz answers must be an array';
  end if;

  select count(*)
  into question_count
  from public.quiz_questions
  where quiz_id = target_quiz_id;

  if question_count = 0 then
    raise exception 'Quiz has no questions';
  end if;

  select count(*)
  into valid_answer_count
  from (
    select distinct answer.question_id
    from jsonb_to_recordset(submitted_answers)
      as answer(question_id bigint, option_id bigint)
    join public.quiz_questions as question
      on question.id = answer.question_id
      and question.quiz_id = target_quiz_id
    join public.quiz_options as quiz_option
      on quiz_option.id = answer.option_id
      and quiz_option.question_id = question.id
  ) as valid_answers;

  if valid_answer_count <> question_count
    or jsonb_array_length(submitted_answers) <> question_count then
    raise exception 'Every quiz question must have one valid answer';
  end if;

  insert into public.quiz_attempts (
    child_id,
    quiz_id,
    correct_answers,
    total_questions,
    score_percent,
    passed
  )
  values (target_child_id, target_quiz_id, 0, question_count, 0, false)
  returning id into created_attempt_id;

  insert into public.quiz_attempt_answers (
    attempt_id,
    question_id,
    selected_option_id,
    is_correct
  )
  select
    created_attempt_id,
    answer.question_id,
    answer.option_id,
    answer.option_id = answer_key.correct_option_id
  from jsonb_to_recordset(submitted_answers)
    as answer(question_id bigint, option_id bigint)
  join public.quiz_questions as question
    on question.id = answer.question_id
    and question.quiz_id = target_quiz_id
  join public.quiz_options as quiz_option
    on quiz_option.id = answer.option_id
    and quiz_option.question_id = question.id
  join public.quiz_answer_keys as answer_key
    on answer_key.question_id = question.id;

  select count(*) filter (where answer.is_correct)
  into correct_count
  from public.quiz_attempt_answers as answer
  where answer.attempt_id = created_attempt_id;

  calculated_percent := round((correct_count::numeric / question_count::numeric) * 100)::integer;
  did_pass := calculated_percent >= required_percent;

  update public.quiz_attempts
  set
    correct_answers = correct_count,
    score_percent = calculated_percent,
    passed = did_pass
  where id = created_attempt_id;

  insert into public.child_lesson_progress as progress (
    child_id,
    lesson_id,
    status,
    progress_percent,
    last_opened_at,
    completed_at
  )
  values (
    target_child_id,
    quiz_lesson_id,
    case when did_pass then 'completed' else 'in_progress' end,
    calculated_percent,
    now()::timestamp without time zone,
    case when did_pass then now()::timestamp without time zone else null end
  )
  on conflict (child_id, lesson_id) do update
  set
    status = case
      when progress.status = 'completed' or excluded.status = 'completed' then 'completed'
      else 'in_progress'
    end,
    progress_percent = greatest(progress.progress_percent, excluded.progress_percent),
    last_opened_at = excluded.last_opened_at,
    completed_at = coalesce(progress.completed_at, excluded.completed_at);

  return query
  select
    created_attempt_id,
    correct_count,
    question_count,
    calculated_percent,
    did_pass;
end;
$$;

revoke all on function public.save_multiple_choice_quiz(bigint, text, text, integer, boolean, jsonb) from public;
revoke all on function public.submit_multiple_choice_quiz(bigint, bigint, jsonb) from public;

grant execute on function public.save_multiple_choice_quiz(bigint, text, text, integer, boolean, jsonb) to authenticated;
grant execute on function public.submit_multiple_choice_quiz(bigint, bigint, jsonb) to authenticated;
