-- Zahlungsvereinbarungen reproduzierbar abbilden und den Namen des
-- verwendeten PayPal- beziehungsweise Bankkontos für neue Registrierungen
-- verpflichtend speichern.

create table if not exists public.payment_agreements (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users (id),
  payment_method text not null
    check (payment_method in ('paypal', 'bank_transfer')),
  payer_name text,
  monthly_amount_cents integer not null default 1499
    check (monthly_amount_cents > 0),
  payment_accepted boolean not null default true,
  accepted_at timestamp with time zone not null default now(),
  agreement_status text not null default 'active'
    check (agreement_status in ('active', 'cancelled')),
  consent_version integer not null default 1,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.monthly_payments (
  id bigint generated by default as identity primary key,
  payment_agreement_id bigint not null
    references public.payment_agreements (id),
  billing_month date not null,
  amount_cents integer not null default 1499
    check (amount_cents > 0),
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'overdue', 'waived')),
  paid_at timestamp with time zone,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.payment_agreements
  add column if not exists payer_name text;

alter table public.payment_agreements
  drop constraint if exists payment_agreements_payer_name_check;

alter table public.payment_agreements
  add constraint payment_agreements_payer_name_check
  check (
    payer_name is null
    or char_length(trim(payer_name)) between 2 and 120
  );

comment on column public.payment_agreements.payer_name is
  'Name des PayPal-Kontos beziehungsweise des Kontoinhabers. Bei vor dieser Migration angelegten Vereinbarungen kann der Wert fehlen.';

-- Falls ein bereits vorhandener Auth-Trigger die Zahlungsvereinbarung anlegt,
-- übernimmt dieser Tabellen-Trigger den Zahlernamen direkt aus den geschützten
-- Auth-Metadaten. Dadurch bleibt die Migration mit dem aktuellen Remote-Stand
-- kompatibel.
create or replace function public.set_payment_agreement_payer_name()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.payer_name := nullif(trim(new.payer_name), '');

  if new.payer_name is null and new.auth_user_id is not null then
    select nullif(trim(account.raw_user_meta_data ->> 'payment_payer_name'), '')
    into new.payer_name
    from auth.users as account
    where account.id = new.auth_user_id;
  end if;

  if new.payer_name is null
    or char_length(new.payer_name) < 2
    or char_length(new.payer_name) > 120 then
    raise exception 'A valid payment payer name is required'
      using errcode = '22023';
  end if;

  return new;
end;
$$;

drop trigger if exists set_payment_agreement_payer_name_before_insert
on public.payment_agreements;

create trigger set_payment_agreement_payer_name_before_insert
before insert on public.payment_agreements
for each row execute procedure public.set_payment_agreement_payer_name();

-- Dieser Trigger läuft alphabetisch nach dem bestehenden Profil-Trigger. Er
-- legt die Vereinbarung an, falls der aktuelle Remote-Trigger das noch nicht
-- erledigt, und ergänzt sie andernfalls konfliktfrei um den Zahlernamen.
create or replace function public.create_new_user_payment_agreement()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_payment_method text;
  selected_payer_name text;
begin
  selected_payment_method :=
    nullif(trim(new.raw_user_meta_data ->> 'payment_method'), '');
  selected_payer_name :=
    nullif(trim(new.raw_user_meta_data ->> 'payment_payer_name'), '');

  if selected_payment_method is null
    or selected_payment_method not in ('paypal', 'bank_transfer') then
    raise exception 'A valid payment method is required'
      using errcode = '22023';
  end if;

  if coalesce(new.raw_user_meta_data ->> 'payment_accepted', 'false') <> 'true' then
    raise exception 'Payment consent is required'
      using errcode = '22023';
  end if;

  if selected_payer_name is null
    or char_length(selected_payer_name) < 2
    or char_length(selected_payer_name) > 120 then
    raise exception 'A valid payment payer name is required'
      using errcode = '22023';
  end if;

  insert into public.payment_agreements (
    auth_user_id,
    payment_method,
    payer_name,
    monthly_amount_cents,
    payment_accepted,
    agreement_status,
    consent_version
  )
  values (
    new.id,
    selected_payment_method,
    selected_payer_name,
    1499,
    true,
    'active',
    1
  )
  on conflict (auth_user_id) do update
  set payment_method = excluded.payment_method,
      payer_name = excluded.payer_name,
      monthly_amount_cents = excluded.monthly_amount_cents,
      payment_accepted = excluded.payment_accepted,
      agreement_status = excluded.agreement_status,
      consent_version = excluded.consent_version,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists zz_on_auth_user_payment_agreement_created
on auth.users;

create trigger zz_on_auth_user_payment_agreement_created
after insert on auth.users
for each row execute procedure public.create_new_user_payment_agreement();

alter table public.payment_agreements enable row level security;
alter table public.monthly_payments enable row level security;

drop policy if exists "Admins can read payment agreements"
on public.payment_agreements;

create policy "Admins can read payment agreements"
on public.payment_agreements
for select
to authenticated
using (public.has_account_role('admin'));

drop policy if exists "Admins can read monthly payments"
on public.monthly_payments;

create policy "Admins can read monthly payments"
on public.monthly_payments
for select
to authenticated
using (public.has_account_role('admin'));

revoke all on table public.payment_agreements from anon;
revoke all on table public.monthly_payments from anon;
revoke all on table public.payment_agreements from authenticated;
revoke all on table public.monthly_payments from authenticated;

grant select on table public.payment_agreements to authenticated;
grant select on table public.monthly_payments to authenticated;

revoke all on function public.set_payment_agreement_payer_name() from public;
revoke all on function public.create_new_user_payment_agreement() from public;
