-- Altersgruppen werden zentral verwaltet und nicht mehr als feste Textwerte gespeichert.

create table public.age_groups (
  id bigint generated by default as identity primary key,
  title text not null unique check (length(trim(title)) > 0),
  min_age smallint not null check (min_age between 0 and 99),
  max_age smallint not null check (max_age between 0 and 99 and max_age >= min_age),
  position integer not null default 0 check (position >= 0),
  created_at timestamp without time zone not null default now(),
  unique (min_age, max_age)
);

insert into public.age_groups (title, min_age, max_age, position)
values
  ('5–8 Jahre', 5, 8, 0),
  ('9–12 Jahre', 9, 12, 1);

alter table public.children
add column age_group_id bigint references public.age_groups (id) on delete restrict;

alter table public.learning_journeys
add column age_group_id bigint references public.age_groups (id) on delete restrict;

alter table public.groups
add column age_group_id bigint references public.age_groups (id) on delete restrict;

update public.children as child
set age_group_id = age_group.id
from public.age_groups as age_group
where (child.age_group = '5-8' and age_group.min_age = 5 and age_group.max_age = 8)
   or (child.age_group = '9-12' and age_group.min_age = 9 and age_group.max_age = 12);

update public.learning_journeys as journey
set age_group_id = age_group.id
from public.age_groups as age_group
where (journey.age_group = '5-8' and age_group.min_age = 5 and age_group.max_age = 8)
   or (journey.age_group = '9-12' and age_group.min_age = 9 and age_group.max_age = 12);

update public.groups as academy_group
set age_group_id = age_group.id
from public.age_groups as age_group
where (academy_group.age_group = '5-8' and age_group.min_age = 5 and age_group.max_age = 8)
   or (academy_group.age_group = '9-12' and age_group.min_age = 9 and age_group.max_age = 12);

alter table public.children alter column age_group_id set not null;
alter table public.learning_journeys alter column age_group_id set not null;
alter table public.groups alter column age_group_id set not null;

alter table public.learning_journeys
drop constraint learning_journeys_academy_year_id_age_group_position_key;

alter table public.children drop column age_group;
alter table public.learning_journeys drop column age_group;
alter table public.groups drop column age_group;

alter table public.learning_journeys
add constraint learning_journeys_year_age_group_position_key
unique (academy_year_id, age_group_id, position);

create index children_age_group_id_idx on public.children (age_group_id);
create index learning_journeys_age_group_id_idx on public.learning_journeys (age_group_id);
create index groups_age_group_id_idx on public.groups (age_group_id);

alter table public.age_groups enable row level security;

create policy "Authenticated users can read age groups"
on public.age_groups
for select
to authenticated
using (true);

create policy "Admins can manage age groups"
on public.age_groups
for all
to authenticated
using (public.has_account_role('admin'))
with check (public.has_account_role('admin'));

revoke all on table public.age_groups from anon;
grant select, insert, update, delete on table public.age_groups to authenticated;
grant usage, select on sequence public.age_groups_id_seq to authenticated;
