-- Mehrere PDF-Dokumente können einer Lektion zugeordnet und innerhalb der
-- freigegebenen Lektion gelesen werden. Die Dateien bleiben im privaten
-- academy-media-Bucket; Familien erhalten nur kurzlebige signierte URLs.

create table public.lesson_documents (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  media_asset_id bigint not null unique references public.media_assets (id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 160),
  position integer not null default 0 check (position >= 0),
  created_at timestamp without time zone not null default now()
);

create index lesson_documents_lesson_position_idx
on public.lesson_documents (lesson_id, position, id);

create or replace function public.validate_lesson_pdf_document()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  linked_asset public.media_assets%rowtype;
begin
  select asset.*
  into linked_asset
  from public.media_assets as asset
  where asset.id = new.media_asset_id;

  if linked_asset.id is null then
    raise exception 'Media asset not found';
  end if;

  if linked_asset.media_type <> 'document'
     or not (
       lower(coalesce(linked_asset.mime_type, '')) = 'application/pdf'
       or lower(linked_asset.file_name) like '%.pdf'
     ) then
    raise exception 'Only PDF lesson documents are allowed';
  end if;

  new.title := trim(new.title);
  return new;
end;
$$;

create trigger validate_lesson_pdf_document_before_write
before insert or update of media_asset_id, title
on public.lesson_documents
for each row execute procedure public.validate_lesson_pdf_document();

alter table public.lesson_documents enable row level security;

create policy "Members can read accessible lesson documents"
on public.lesson_documents
for select
to authenticated
using (
  public.is_academy_staff()
  or exists (
    select 1
    from public.lessons as lesson
    join public.learning_journeys as journey
      on journey.id = lesson.learning_journey_id
    join public.academy_years as academy_year
      on academy_year.id = journey.academy_year_id
    where lesson.id = lesson_documents.lesson_id
      and lesson.status = 'published'
      and lesson.is_released
      and journey.is_published
      and academy_year.is_active
      and public.can_access_age_group_learning_content(
        journey.age_group_id,
        journey.academy_year_id
      )
  )
);

create policy "Admins can manage lesson documents"
on public.lesson_documents
for all
to authenticated
using (public.has_account_role('admin'))
with check (public.has_account_role('admin'));

-- Diese SECURITY-DEFINER-Funktion wird sowohl von der Metadaten- als auch
-- von der Storage-Policy genutzt. So genügt das Erraten eines Objektpfads
-- nicht, um ein gesperrtes PDF abzurufen.
create or replace function public.can_access_academy_media_object(
  target_bucket text,
  target_path text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_academy_staff()
    or exists (
      select 1
      from public.media_assets as asset
      join public.lesson_documents as document
        on document.media_asset_id = asset.id
      join public.lessons as lesson
        on lesson.id = document.lesson_id
      join public.learning_journeys as journey
        on journey.id = lesson.learning_journey_id
      join public.academy_years as academy_year
        on academy_year.id = journey.academy_year_id
      where asset.bucket_name = target_bucket
        and asset.storage_path = target_path
        and lesson.status = 'published'
        and lesson.is_released
        and journey.is_published
        and academy_year.is_active
        and public.can_access_age_group_learning_content(
          journey.age_group_id,
          journey.academy_year_id
        )
    )
$$;

create or replace function public.can_manage_academy_media_object(
  target_bucket text,
  target_path text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_academy_staff()
    and (
      public.has_account_role('admin')
      or not exists (
        select 1
        from public.media_assets as asset
        join public.lesson_documents as document
          on document.media_asset_id = asset.id
        where asset.bucket_name = target_bucket
          and asset.storage_path = target_path
      )
    )
$$;

revoke all on function public.validate_lesson_pdf_document()
from public;
revoke all on function public.can_access_academy_media_object(text, text)
from public;
revoke all on function public.can_manage_academy_media_object(text, text)
from public;

grant execute on function public.can_access_academy_media_object(text, text)
to authenticated;
grant execute on function public.can_manage_academy_media_object(text, text)
to authenticated;

drop policy if exists "Members can read academy media"
on public.media_assets;

create policy "Members can read accessible academy media"
on public.media_assets
for select
to authenticated
using (
  public.can_access_academy_media_object(bucket_name, storage_path)
);

drop policy if exists "Staff can manage academy media"
on public.media_assets;

create policy "Staff can add academy media"
on public.media_assets
for insert
to authenticated
with check (public.is_academy_staff());

create policy "Staff can update manageable academy media"
on public.media_assets
for update
to authenticated
using (
  public.can_manage_academy_media_object(bucket_name, storage_path)
)
with check (
  public.can_manage_academy_media_object(bucket_name, storage_path)
);

create policy "Staff can delete manageable academy media"
on public.media_assets
for delete
to authenticated
using (
  public.can_manage_academy_media_object(bucket_name, storage_path)
);

drop policy if exists "Members can read academy media objects"
on storage.objects;

create policy "Members can read accessible academy media objects"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'academy-media'
  and public.can_access_academy_media_object(bucket_id, name)
);

drop policy if exists "Staff can update academy media objects"
on storage.objects;
drop policy if exists "Staff can delete academy media objects"
on storage.objects;

create policy "Staff can update manageable academy media objects"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'academy-media'
  and public.can_manage_academy_media_object(bucket_id, name)
)
with check (
  bucket_id = 'academy-media'
  and public.can_manage_academy_media_object(bucket_id, name)
);

create policy "Staff can delete manageable academy media objects"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'academy-media'
  and public.can_manage_academy_media_object(bucket_id, name)
);

revoke all on table public.lesson_documents from anon;
grant select, insert, update, delete on table public.lesson_documents
to authenticated;
grant usage, select on sequence public.lesson_documents_id_seq
to authenticated;

comment on table public.lesson_documents is
  'PDF documents shown as protected readers inside an accessible lesson.';
